### ISSUE TITLE
Can`t compile with GCC 12.0.1 Win11

### ISSUE THREAD

**Issue by necros2k7** [JayXon/Leanify#65]

**Comment by JayXon** [comment]
What's ByteArray.c? That's not a source file in leanify.

Maybe trying appending a space after Leanify.res in build_gcc.bat line 4? I haven't used that in a while it could be broken.

**Comment by necros2k7** [comment]
Sorry I edited 1st post my bad, and yes space helped but still after some processing gives:

Z:\LEANIFY>build_gcc
lib\zopfli\squeeze.c: In function 'double LZ77OptimalRun(ZopfliBlockState*, const unsigned char*, size_t, size_t, short unsigned int**, size_t*, short unsigned int*, void*, ZopfliLZ77Store*, ZopfliHash*, float*)':
lib\zopfli\squeeze.c:430:17: error: invalid conversion from 'void*' to 'SymbolStats*' [-fpermissive]
  430 |                 costcontext, length_array, h, costs);
      |                 ^~~~~~~~~~~
      |                 |
      |                 void*
lib\zopfli\squeeze.c:191:43: note:   initializing argument 5 of 'double GetBestLengths(ZopfliBlockState*, const unsigned char*, size_t, size_t, SymbolStats*, short unsigned int*, ZopfliHash*, float*)'
  191 |                              SymbolStats* costcontext,
      |                              ~~~~~~~~~~~~~^~~~~~~~~~~

**Comment by JayXon** [comment]
What's "═х єфрхЄё  эрщЄш єърчрээ√щ Їрщы."? Looks like russian, could you translate that? But probably something wrong with your mingw setup.

That error in build_gcc looks like it's caused by using g++ on .c files, at this point, I'll probably just delete build_gcc and just use Makefile or visual studio.

**Comment by necros2k7** [comment]
Translates into:
make (e=2): Can`t find given file
